### ISSUE TITLE
Spacebar to start and disclaimer

### ISSUE THREAD

**Issue by SaumyashreeRay** [mcay23/COMP580HauntedHouse#2]
"Space bar to start" works on Mozilla only after clicking on the screen. Also the disclaimer doesn't speak out loud everything on the page. Not sure if this is a necessary issue, but wanted to point it out

**Comment by TianL520** [comment]
Hi, we fixed the issue with the "space bar to start." Players can now directly start playing after they press the spacebar. 
In terms of your second issue, we did this on purpose because this game is meant to be replayable because it includes multiple endings. We didn't want the players to listen to the entire disclaimer every time they play the game, thus we decided to only read out the first two sentences. We wrote the entire disclaimer in the readme, so people can use the screen reader if they needed to listen to the entire thing.
